# Generated by Django 4.2.7 on 2025-07-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('orders', '0003_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.promotioncode'),
        ),
    ]
