# Generated by Django 4.2.7 on 2025-07-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_promotion_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipstation_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('ontrac', 'OnTrac'), ('lasership', 'LaserShip'), ('canadapost', 'Canada Post'), ('dpd', 'DPD'), ('gls', 'GLS'), ('purolator', 'Purolator'), ('asendia', 'Asendia'), ('other', 'Other')], help_text='Shipping carrier', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_label_url',
            field=models.URLField(blank=True, help_text='Goshippo shipping label URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_object_id',
            field=models.CharField(blank=True, help_text='Goshippo shipment object ID', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_order_id',
            field=models.CharField(blank=True, help_text='Goshippo order ID', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_rate_id',
            field=models.CharField(blank=True, help_text='Goshippo rate ID used for shipping', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_tracking_url',
            field=models.URLField(blank=True, help_text='Goshippo tracking URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='goshippo_transaction_id',
            field=models.CharField(blank=True, help_text='Goshippo transaction ID', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='service_level',
            field=models.CharField(blank=True, choices=[('usps_priority', 'USPS Priority Mail'), ('usps_priority_express', 'USPS Priority Mail Express'), ('usps_ground_advantage', 'USPS Ground Advantage'), ('usps_first_class', 'USPS First Class'), ('usps_media_mail', 'USPS Media Mail'), ('ups_ground', 'UPS Ground'), ('ups_next_day_air', 'UPS Next Day Air'), ('ups_next_day_air_saver', 'UPS Next Day Air Saver'), ('ups_2nd_day_air', 'UPS 2nd Day Air'), ('ups_3_day_select', 'UPS 3 Day Select'), ('fedex_ground', 'FedEx Ground'), ('fedex_express_saver', 'FedEx Express Saver'), ('fedex_2_day', 'FedEx 2Day'), ('fedex_standard_overnight', 'FedEx Standard Overnight'), ('fedex_priority_overnight', 'FedEx Priority Overnight'), ('dhl_express', 'DHL Express'), ('dhl_express_worldwide', 'DHL Express Worldwide'), ('dhl_economy_select', 'DHL Economy Select'), ('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight'), ('other', 'Other')], help_text='Service level', max_length=100),
        ),
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goshippo_tracking_id', models.CharField(blank=True, help_text='Goshippo tracking object ID', max_length=50)),
                ('tracking_number', models.CharField(help_text='Package tracking number', max_length=100)),
                ('carrier', models.CharField(choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('ontrac', 'OnTrac'), ('lasership', 'LaserShip'), ('canadapost', 'Canada Post'), ('dpd', 'DPD'), ('gls', 'GLS'), ('purolator', 'Purolator'), ('asendia', 'Asendia'), ('other', 'Other')], help_text='Shipping carrier', max_length=50)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PRE_TRANSIT', 'Pre Transit'), ('TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('FAILURE', 'Failure')], default='UNKNOWN', max_length=20)),
                ('status_details', models.TextField(blank=True, help_text='Detailed status message')),
                ('status_date', models.DateTimeField(blank=True, help_text='When the status occurred', null=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('goshippo_object_created', models.DateTimeField(blank=True, null=True)),
                ('goshippo_object_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_statuses', to='orders.order')),
            ],
            options={
                'verbose_name': 'Tracking Status',
                'verbose_name_plural': 'Tracking Statuses',
                'ordering': ['-status_date', '-created_at'],
            },
        ),
    ]
