# Generated by Django 4.2.7 on 2025-07-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_low_stock_threshold_product_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
