# Generated by Django 4.2.7 on 2025-07-04 06:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_low_stock_threshold_product_search_vector_and_more'),
        ('orders', '0003_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_type', models.CharField(choices=[('single', 'Single Use'), ('limited', 'Limited Uses'), ('unlimited', 'Unlimited Uses')], default='unlimited', max_length=20)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this code can be used', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Number of times a single user can use this code')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this code', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_to_all', models.BooleanField(default=True)),
                ('first_order_only', models.BooleanField(default=False, help_text="Code can only be used on user's first order")),
                ('logged_in_only', models.BooleanField(default=False, help_text='Code can only be used by logged-in users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, to='products.product')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('promotion_codes', models.ManyToManyField(blank=True, related_name='campaigns', to='promotions.promotioncode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='promotions.promotioncode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('promotion_code', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=models.Index(fields=['code', 'is_active'], name='promotions__code_5f84ee_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotions__valid_f_c4aeb1_idx'),
        ),
    ]
