# Generated by Django 4.2.7 on 2025-07-04 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_low_stock_threshold_product_search_vector_and_more'),
        ('orders', '0002_order_session_key_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('feature', models.CharField(max_length=100)),
                ('variants', models.JSONField(default=list, help_text='List of variant configurations')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('traffic_percentage', models.IntegerField(default=100, help_text='Percentage of traffic to include in test')),
                ('success_metric', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_ab_experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('customer', 'Customer Report'), ('product', 'Product Performance'), ('marketing', 'Marketing Report'), ('financial', 'Financial Report'), ('custom', 'Custom Report')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('search', 'Search'), ('filter', 'Filter'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Start'), ('checkout_complete', 'Checkout Complete'), ('form_submit', 'Form Submit'), ('error', 'Error'), ('custom', 'Custom')], max_length=50)),
                ('event_name', models.CharField(max_length=255)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('page_url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_behavior',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_u_timesta_006ec3_idx'), models.Index(fields=['user'], name='analytics_u_user_id_adc136_idx'), models.Index(fields=['session_id'], name='analytics_u_session_191e07_idx'), models.Index(fields=['event_type'], name='analytics_u_event_t_f7ff5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_duration', models.IntegerField(blank=True, help_text='View duration in seconds', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the view (search, category, recommendation, etc.)', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_product_views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_1666e3_idx'), models.Index(fields=['user'], name='analytics_p_user_id_848906_idx'), models.Index(fields=['product'], name='analytics_p_product_54d976_idx'), models.Index(fields=['session_id'], name='analytics_p_session_b73cf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('page_url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_page_views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_2db77e_idx'), models.Index(fields=['user'], name='analytics_p_user_id_9f2249_idx'), models.Index(fields=['session_id'], name='analytics_p_session_3152bc_idx'), models.Index(fields=['page_url'], name='analytics_p_page_ur_c3e732_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('landing_page', models.URLField(blank=True, max_length=500)),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribution_data', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_conversions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_c_timesta_46dff7_idx'), models.Index(fields=['user'], name='analytics_c_user_id_2ca19b_idx'), models.Index(fields=['source', 'medium', 'campaign'], name='analytics_c_source_ddf6e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('cart_data', models.JSONField(default=dict)),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abandoned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_cart_abandonment',
                'ordering': ['-abandoned_at'],
                'indexes': [models.Index(fields=['abandoned_at'], name='analytics_c_abandon_4f6751_idx'), models.Index(fields=['user'], name='analytics_c_user_id_b2a028_idx'), models.Index(fields=['recovered'], name='analytics_c_recover_837184_idx')],
            },
        ),
        migrations.CreateModel(
            name='ABTestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('variant', models.CharField(max_length=50)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted', models.BooleanField(default=False)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_data', models.JSONField(blank=True, default=dict)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='analytics.abtestexperiment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_ab_participants',
                'indexes': [models.Index(fields=['experiment', 'variant'], name='analytics_a_experim_521077_idx'), models.Index(fields=['enrolled_at'], name='analytics_a_enrolle_479201_idx')],
                'unique_together': {('experiment', 'user', 'session_id')},
            },
        ),
    ]
