# AlertManager Configuration for Pasargad Prints

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@pasargadprints.com'
  smtp_auth_username: 'alerts@pasargadprints.com'
  smtp_auth_password: 'your-smtp-password'
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
      routes:
        # Database critical alerts
        - match:
            team: devops
        receiver: 'devops-critical'
        # Application critical alerts
        - match:
            team: development
          receiver: 'dev-critical'
        # Security critical alerts
        - match:
            team: security
          receiver: 'security-critical'

    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

    # Business alerts
    - match:
        team: operations
      receiver: 'business-alerts'

    # Maintenance window - suppress alerts
    - match:
        alertname: 'MaintenanceMode'
      receiver: 'null'

# Inhibition rules - suppress alerts based on other alerts
inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

  # Suppress individual service alerts when entire application is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match_re:
      alertname: '(HighErrorRate|SlowResponseTime|DatabaseDown)'
    equal: ['cluster']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 'devops@pasargadprints.com'
        subject: '[ALERT] {{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt }}
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@pasargadprints.com,management@pasargadprints.com'
        subject: '🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        html: |
          <h2>🚨 Critical Alert</h2>
          <table border="1">
            <tr><th>Alert</th><th>Severity</th><th>Started</th><th>Description</th></tr>
            {{ range .Alerts }}
            <tr>
              <td>{{ .Labels.alertname }}</td>
              <td>{{ .Labels.severity }}</td>
              <td>{{ .StartsAt }}</td>
              <td>{{ .Annotations.description }}</td>
            </tr>
            {{ end }}
          </table>
          <p><strong>Action required immediately!</strong></p>
    slack_configs:
      - channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Severity:* {{ .Labels.severity }}
          *Description:* {{ .Annotations.description }}
          *Started:* {{ .StartsAt }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        color: 'danger'

  # DevOps critical alerts
  - name: 'devops-critical'
    email_configs:
      - to: 'devops@pasargadprints.com'
        subject: '🚨 DEVOPS CRITICAL: {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#devops-alerts'
        title: '🚨 DevOps Critical Alert'
        color: 'danger'
    pagerduty_configs:
      - routing_key: 'your-pagerduty-integration-key'
        description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'

  # Development critical alerts
  - name: 'dev-critical'
    email_configs:
      - to: 'dev@pasargadprints.com'
        subject: '🚨 DEV CRITICAL: {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#dev-alerts'
        title: '🚨 Development Critical Alert'
        color: 'danger'

  # Security critical alerts
  - name: 'security-critical'
    email_configs:
      - to: 'security@pasargadprints.com,management@pasargadprints.com'
        subject: '🔒 SECURITY CRITICAL: {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#security-alerts'
        title: '🔒 Security Critical Alert'
        color: 'danger'

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@pasargadprints.com'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        body: |
          Warning Alert Triggered:
          
          {{ range .Alerts }}
          Alert: {{ .Labels.alertname }}
          Severity: {{ .Labels.severity }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
    slack_configs:
      - channel: '#alerts-warning'
        title: '⚠️ Warning Alert'
        color: 'warning'

  # Business/Operations alerts
  - name: 'business-alerts'
    email_configs:
      - to: 'operations@pasargadprints.com'
        subject: '📊 BUSINESS ALERT: {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#business-alerts'
        title: '📊 Business Alert'
        color: 'good'

  # Null receiver for suppressed alerts
  - name: 'null'

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'