# Prometheus Configuration for Pasargad Prints Production

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pasargad-prints-prod'
    environment: 'production'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:
  # Django Application
  - job_name: 'pasargad-prints-app'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/api/monitoring/prometheus/'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: https
    tls_config:
      insecure_skip_verify: false
    basic_auth:
      username: 'monitoring'
      password: 'monitoring_password'

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Nginx Web Server
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    scrape_interval: 30s

  # Celery Workers
  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:9540']
    scrape_interval: 30s

  # Blackbox Exporter (Synthetic Monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://pasargadprints.com
        - https://api.pasargadprints.com/health/
        - https://pasargadprints.com/login
        - https://pasargadprints.com/shop
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093
      timeout: 10s
      path_prefix: /

# Storage configuration
storage:
  tsdb:
    path: /var/lib/prometheus/
    retention.time: 30d
    retention.size: 10GB

# Remote write (for long-term storage)
remote_write:
  - url: "https://your-prometheus-remote-write-endpoint"
    basic_auth:
      username: "your-username"
      password: "your-password"
    queue_config:
      capacity: 2500
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms